package cxf.client.postalcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-03-09T20:52:41.193-06:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", name = "IPostalCodeService")
@XmlSeeAlso({ObjectFactory.class})
public interface IPostalCodeService {

    @WebResult(name = "GetPostCodeDetailsByPlaceNameResult", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
    @Action(input = "GetPostCodeDetailsByPlaceName", output = "http://www.restfulwebservices.net/ServiceContracts/2008/01/IPostalCodeService/GetPostCodeDetailsByPlaceNameResponse", fault = {@FaultAction(className = IPostalCodeServiceGetPostCodeDetailsByPlaceNameDefaultFaultContractFaultFaultMessage.class, value = "http://www.restfulwebservices.net/ServiceContracts/2008/01/IPostalCodeService/GetPostCodeDetailsByPlaceNameDefaultFaultContractFault")})
    @RequestWrapper(localName = "GetPostCodeDetailsByPlaceName", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "cxf.client.postalcode.GetPostCodeDetailsByPlaceName")
    @WebMethod(operationName = "GetPostCodeDetailsByPlaceName", action = "GetPostCodeDetailsByPlaceName")
    @ResponseWrapper(localName = "GetPostCodeDetailsByPlaceNameResponse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "cxf.client.postalcode.GetPostCodeDetailsByPlaceNameResponse")
    public cxf.client.postalcode.PostalCode getPostCodeDetailsByPlaceName(
        @WebParam(name = "request", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        java.lang.String request
    ) throws IPostalCodeServiceGetPostCodeDetailsByPlaceNameDefaultFaultContractFaultFaultMessage;

    @WebResult(name = "GetPostCodeDetailByPostCodeResult", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
    @Action(input = "GetPostCodeDetailByPostCode", output = "http://www.restfulwebservices.net/ServiceContracts/2008/01/IPostalCodeService/GetPostCodeDetailByPostCodeResponse", fault = {@FaultAction(className = IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage.class, value = "http://www.restfulwebservices.net/ServiceContracts/2008/01/IPostalCodeService/GetPostCodeDetailByPostCodeDefaultFaultContractFault")})
    @RequestWrapper(localName = "GetPostCodeDetailByPostCode", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "cxf.client.postalcode.GetPostCodeDetailByPostCode")
    @WebMethod(operationName = "GetPostCodeDetailByPostCode", action = "GetPostCodeDetailByPostCode")
    @ResponseWrapper(localName = "GetPostCodeDetailByPostCodeResponse", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01", className = "cxf.client.postalcode.GetPostCodeDetailByPostCodeResponse")
    public cxf.client.postalcode.PostalCode getPostCodeDetailByPostCode(
        @WebParam(name = "request", targetNamespace = "http://www.restfulwebservices.net/ServiceContracts/2008/01")
        java.lang.String request
    ) throws IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage;
}
