
package cxf.client.postalcode;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-03-09T20:52:41.181-06:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "DefaultFaultContract", targetNamespace = "http://GOTLServices.FaultContracts/2008/01")
public class IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage extends Exception {
    
    private cxf.client.postalcode.DefaultFaultContract defaultFaultContract;

    public IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage() {
        super();
    }
    
    public IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage(String message) {
        super(message);
    }
    
    public IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage(String message, cxf.client.postalcode.DefaultFaultContract defaultFaultContract) {
        super(message);
        this.defaultFaultContract = defaultFaultContract;
    }

    public IPostalCodeServiceGetPostCodeDetailByPostCodeDefaultFaultContractFaultFaultMessage(String message, cxf.client.postalcode.DefaultFaultContract defaultFaultContract, Throwable cause) {
        super(message, cause);
        this.defaultFaultContract = defaultFaultContract;
    }

    public cxf.client.postalcode.DefaultFaultContract getFaultInfo() {
        return this.defaultFaultContract;
    }
}
